TYPO3:
  Flow:
    security:
      firewall:
        rejectAll: FALSE

        filters:
          'Netlogix.Aws.ElasticBeanstalk:WorkerFromInternet':
            pattern: 'Netlogix\Aws\ElasticBeanstalk\RequestPattern\WorkerAccessFromInternet'
            patternOptions: {}
            interceptor:  'AccessDeny'

Flowpack:
  JobQueue:
    Common:
      queues:
        'awseb-fakequeue':
          className: 'Flowpack\JobQueue\Common\Queue\FakeQueue'
          options:
            async: false
