TYPO3:
  Flow:
    security:
      firewall:
        rejectAll: FALSE

        filters:
          'Netlogix.Aws.ElasticBeanstalk:WorkerFromInternet':
            pattern: 'Netlogix\Aws\ElasticBeanstalk\RequestPattern\WorkerAccessFromInternet'
            patternOptions: {}
            interceptor:  'AccessDeny'
